---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: vanus-operator
rules:
- apiGroups:
  - vanus.linkall.com
  resources:
  - controllers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.linkall.com
  resources:
  - controllers/finalizers
  verbs:
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - controllers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.linkall.com
  resources:
  - stores/finalizers
  verbs:
  - update
- apiGroups:
  - vanus.linkall.com
  resources:
  - stores/status
  verbs:
  - get
  - patch
  - update
